### ISSUE TITLE
Allow Jest to run ESM modules

### ISSUE THREAD

**Issue by millsp** [prisma/engines-wrapper#133]
### Bug description

Some modules cannot be upgraded because they use ESM syntax. In turn, our tests fail.

### How to reproduce

For example see https://github.com/prisma/engines-wrapper/pull/131

### Expected behavior

We should be able to run the tests since we are able to compile ES modules.

**Comment by Jolg42** [comment]
Tracked in https://github.com/prisma/prisma/issues/7618
