### ISSUE TITLE
Manual Engines releases (in branches/PRs) create a normal engines-wrapper release here, but nothing on `prisma/prisma`

### ISSUE THREAD

**Issue by janpio** [prisma/engines-wrapper#161]
Example:
https://github.com/prisma/prisma-engines/pull/2208 (original)
https://github.com/prisma/prisma-engines/pull/2196 (copy in our repo)
https://buildkite.com/prisma/release-prisma-engines/builds/1596
https://github.com/prisma/engines-wrapper/actions/runs/1197982488
https://github.com/prisma/engines-wrapper/runs/3506044105?check_suite_focus=true
https://github.com/prisma/engines-wrapper/commit/b112a3a601bb36d8a0ce7e4dab58b0b7b5903162
`2.31.0-25.node-api-threadsafe-unref-1ca259332bad49e28dd3eda822c358a766b3ec08`

See how the GH Actions run skips the `Workflow dispatch to prisma/prisma for version update` step. One way this is great, as it does not automatically create a new `dev` version. On the other hand we do not get an automatic version with this engine.

Should maybe auto create an `integration` branch of the same name and open a PR? (via triggering a special version of the workflow on `prisma/prisma`)

**Comment by Jolg42** [comment]
Note: the current action config is here
https://github.com/prisma/engines-wrapper/blob/main/.github/workflows/publish-engines.yml#L40:L42
```
      - name: Workflow dispatch to prisma/prisma for version update
        # Only automatically trigger update for `latest`!
        if: steps.publish_script.outputs.npm_dist_tag == 'latest'
```

**Comment by Jolg42** [comment]
This issue is outdated. see
https://github.com/prisma/schema-team/issues/358
https://github.com/prisma/prisma-engines#automated-integration-releases-from-this-repository-to-npm
