### ISSUE TITLE
Extract `@prisma/debug` into its own repository

### ISSUE THREAD

**Issue by millsp** [prisma/engines-wrapper#169]
The goal of this is to have a clean architecture where `prisma/prisma` depends on `prisma/engines-wrapper`. At the moment `prisma/prisma` depends on `prisma/engines-wrapper` that depends on `prisma/prisma` through `@prisma/debug`.

To avoid maintenance burden, instead of separating it into another repo, we could change our publish script to only publish to only publish (ie. `@prisma/debug`) if it has changes to be published. We can also argue that `@prisma/debug` is a tool that does not even depend on the engines an is thus not subject to the same versioning. This could be the opportunity to set up a new repo for tools and manage it perhaps via [changesets](https://github.com/atlassian/changesets).

Context https://prisma-company.slack.com/archives/CUXLS0Z6K/p1631084401029500

**Comment by Jolg42** [comment]
Since packages moved to prisma/prisma this can now be closed
